export const linkedinIndustries = [
  'Accounting',
  'Advertising Services',
  'Aerospace',
  'Agriculture',
  'AI and Automation',
  'Architecture',
  'Automotive',
  'Banking',
  'Biotechnology',
  'Business Consulting',
  'Civil Engineering',
  'Computer Games',
  'Computer Hardware',
  'Construction',
  'Consumer Goods',
  'Cybersecurity',
  'Design Services',
  'Ecommerce',
  'Education',
  'Energy',
  'Entertainment',
  'Environmental Services',
  'Events Services',
  'Financial Services',
  'Food and Beverage',
  'Government',
  'Healthcare',
  'Higher Education',
  'Hospitality',
  'Human Resources',
  'Information Technology',
  'Insurance',
  'Internet Publishing',
  'Investment Management',
  'Legal Services',
  'Logistics',
  'Manufacturing',
  'Marketing Agencies',
  'Media Production',
  'Medical Devices',
  'Nonprofit',
  'Oil and Gas',
  'Pharmaceuticals',
  'Professional Training',
  'Real Estate',
  'Recruitment',
  'Retail',
  'SaaS',
  'Software Development',
  'Telecommunications',
  'Transportation',
  'Venture Capital',
  'Wholesale',
]

export const linkedinRoles = [
  'Account Executive',
  'Agency Founder',
  'BDR',
  'Broker Owner',
  'Business Development Manager',
  'CEO',
  'CFO',
  'Chief Marketing Officer',
  'Chief Operating Officer',
  'Chief Revenue Officer',
  'Clinic Director',
  'Consultant',
  'Customer Success Manager',
  'Demand Generation Manager',
  'Director of Sales',
  'Ecommerce Director',
  'Founder',
  'General Manager',
  'Growth Lead',
  'Head of Marketing',
  'Head of Operations',
  'Head of Partnerships',
  'Head of Product',
  'Head of Sales',
  'HR Director',
  'Managing Director',
  'Managing Partner',
  'Marketing Director',
  'Operations Manager',
  'Owner',
  'Partnerships Manager',
  'Product Manager',
  'Recruiter',
  'Recruitment Manager',
  'Revenue Operations Manager',
  'Sales Development Representative',
  'Sales Director',
  'Sales Manager',
  'Sales Operations Manager',
  'Talent Acquisition Lead',
  'VP Growth',
  'VP Marketing',
  'VP Operations',
  'VP Sales',
]

export const leadFinderCountries = [
  'United States',
  'Canada',
  'United Kingdom',
  'Australia',
  'India',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Netherlands',
  'Singapore',
  'United Arab Emirates',
  'Brazil',
  'Mexico',
  'Japan',
  'South Korea',
  'Indonesia',
  'Philippines',
  'Malaysia',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Saudi Arabia',
  'Qatar',
  'New Zealand',
  'Ireland',
  'Sweden',
  'Norway',
  'Denmark',
  'Switzerland',
  'Belgium',
  'Poland',
  'Portugal',
  'Argentina',
  'Chile',
  'Colombia',
]
